KNUStudySystem/KNUStudySystem/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using KNUStudySystem.Models;
using System.Diagnostics;
using Assignment = KNUStudySystem.Models.Assignment;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using System;
using Microsoft.AspNetCore.Authorization;
using System.Linq;
using System.Threading.Tasks;

namespace KNUStudySystem.Controllers
{
    public class AssignmentController : Controller
    {
        private readonly ILogger<AssignmentController> _logger;
        private readonly Database _database;

        public AssignmentController(ILogger<AssignmentController> logger, Database database)
        {
            _logger = logger;
            _database = database;
        }

        public IActionResult Index()
        {
            List<Assignment> assignments = new List<Assignment>();
            using (var connection = _database.getConnectionToDb())
            {
                connection.Open();
                _database.setCommand("SELECT * FROM Tasks");
                MySqlCommand command = _database.getExecutableCommand(connection);
                MySqlDataReader reader = command.ExecuteReader();
                while (reader.Read())
                {
                    Assignment assignment = new Assignment();
                    assignment.Id = Convert.ToInt32(reader["task_id"]);
                    assignment.Assignment_Name = Convert.ToString(reader["task_name"]);
                    assignment.Assignment_Type = Convert.ToString(reader["task_type"]);
                    assignment.Assignment_Description = Convert.ToString(reader["task_description"]);
                    assignment.File_Id = Convert.ToString(reader["file_id"]);
                    assignment.Subject = Convert.ToString(reader["subject"]);
                    assignment.Department = Convert.ToString(reader["department"]);
                    assignment.Speciality = Convert.ToString(reader["speciality"]);
                    assignment.Course = Convert.ToInt32(reader["course"]);
                    assignment.Group = Convert.ToInt32(reader["group"]);
                    assignment.Assignment_Date = Convert.ToDateTime(reader["task_date"]);
                    assignment.Deadline = Convert.ToDateTime(reader["deadline"]);

                    assignments.Add(assignment);
                }
                reader.Close();
                connection.Close();
            }
            return View(assignments);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KNUStudySystem/KNUStudySystem/Controllers/MarkController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using KNUStudySystem.Models;
using System.Diagnostics;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using MySql.Data.MySqlClient;
using System.Linq;
using KNUStudySystem.ViewModels;

namespace KNUStudySystem.Controllers
{
    public class MarkController : Controller
    {
        private readonly ILogger<MarkController> _logger;
        private readonly Database _database;

        public MarkController(ILogger<MarkController> logger, Database database)
        {
            _logger = logger;
            _database = database;
        }

        private List<Mark> ParseDB(string filters)
        {
            List<Mark> marks = new List<Mark>();
            using (var connection = _database.getConnectionToDb())
            {
                connection.Open();
                _database.setCommand("SELECT Tasks.task_id, Tasks.task_name, Tasks.subject, " +
                    "Tasks.task_type, Marks.id, Marks.comment, Marks.grade,  " +
                    "Marks.teacher, Marks.evaluation_date, Marks.status " +
                    "FROM Tasks JOIN Marks ON Tasks.task_id = Marks.task_id " +
                    "WHERE task_name LIKE \'" + filters + "%\'");
                using var command = _database.getExecutableCommand(connection);
                using var reader = command.ExecuteReader();
                while (reader.Read())
                {
                    Mark mark = new Mark();
                    mark.Id = Convert.ToInt32(reader["id"]);
                    mark.TaskId = Convert.ToInt32(reader["task_id"]);
                    mark.TaskName = Convert.ToString(reader["task_name"]);
                    mark.TaskType = Convert.ToString(reader["task_type"]);
                    mark.Comment = Convert.ToString(reader["comment"]);
                    mark.Subject = Convert.ToString(reader["subject"]);
                    mark.Grade = Convert.ToInt32(reader["grade"]);
                    mark.Teacher = Convert.ToString(reader["teacher"]);
                    mark.EvaluationDate = Convert.ToDateTime(reader["evaluation_date"]);
                    switch (reader["status"])
                    {
                        case "COMPLETED":
                            mark.Status = status.completed;
                            break;
                        case "FAILED":
                            mark.Status = status.failed;
                            break;
                    }
                    marks.Add(mark);
                }
                reader.Close();
                connection.Close();
            }
            return marks;
        }

        public IActionResult Index(bool ascending, string sortBy = null, /*List<Filter> filters*/string filters = null  )
        {
            MarkFilteredViewModel MarksView = new MarkFilteredViewModel();

            MarksView.Ascending = ascending;
            if (sortBy == null)
                sortBy = "Evaluation Date";
            MarksView.SortBy = sortBy;
            //MarksView.Filters = filters;
            MarksView.Marks = ParseDB(filters);
            if (sortBy == "Evaluation Date")
                MarksView.Marks = MarksView.Marks.OrderBy(o => o.EvaluationDate).ToList();
            else if (sortBy == "Name")
                MarksView.Marks = MarksView.Marks.OrderBy(o => o.TaskName).ToList();
            else if (sortBy == "Grade")
                MarksView.Marks = MarksView.Marks.OrderBy(o => o.Grade).ToList();
            if (!ascending)
                MarksView.Marks.Reverse();
            return View(MarksView);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KNUStudySystem/KNUStudySystem/Controllers/MaterialsController.cs
using KNUStudySystem.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KNUStudySystem.Controllers
{
    public class MaterialsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KNUStudySystem/KNUStudySystem/Controllers/RolesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using KNUStudySystem.Models;
using KNUStudySystem.ViewModels;
using KNUStudySystem.Areas.Identity.Data;
using Microsoft.AspNetCore.Authorization;
using System.Dynamic;
using Microsoft.AspNetCore.Razor.TagHelpers;
using MySql.Data.MySqlClient;

namespace KNUStudySystem.Controllers
{
    /*[Authorize(Roles = "Адміністратор")]*/
    [AllowAnonymous]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        UserManager<AppUser> _userManager;
        private readonly Database _database;
        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager, Database database)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _database = database;

        }
        public IActionResult Index() => View(_roleManager.Roles.ToList());

        public IActionResult Create() => View();
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList() => View(_userManager.Users.ToList());

        public async Task<IActionResult> Edit(string userId)
        {
            // получаем пользователя
            AppUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.FirstName + " " + user.LastName,
                    UserEmail = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            // получаем пользователя
            AppUser user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                // получем список ролей пользователя
                var user_roles = await _userManager.GetRolesAsync(user);
                // получаем все роли
                var all_roles = _roleManager.Roles.ToList();
                // получаем список ролей, которые были добавлены
                var added_roles = roles.Except(user_roles);
                // получаем роли, которые были удалены
                var removed_roles = user_roles.Except(roles);
                if (added_roles.Contains("Викладач"))
                {
                    Teacher teacher = new Teacher
                    {
                        UserId = user.Id,
                        UserName = user.UserName
                    };
                    teacher.AddInfoToDb(_database);
                }
                if (removed_roles.Contains("Викладач"))
                {
                    Teacher teacher = new Teacher();
                    teacher.UserId = user.Id;
                    teacher.DeleteInfoFromDb(_database);
                }
                if (removed_roles.Contains("Студент"))
                {
                    Student student = new Student();
                    student.UserId = user.Id;
                    student.DeleteInfoFromDb(_database);
                }    
                await _userManager.AddToRolesAsync(user, added_roles);

                await _userManager.RemoveFromRolesAsync(user, removed_roles);
                
                

                return RedirectToAction("UserList");
            }

            return NotFound();
        }
    }
}

KNUStudySystem/KNUStudySystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] -KNUStudySystem</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
        <script src="https://kit.fontawesome.com/8cd4cc108d.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/header.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/footer.css" asp-append-version="true">
        <link rel="stylesheet" href="~/css/style.css" asp-append-version="true">
    </head>
    <body>
        <header>
            <div class="header__row borders-margin">
                <div class="logo back-image"></div>
                <nav>
                    <ul>
                        <li>
                            <a class = "header__menu-element pointer" asp-area="" asp-controller="Home" asp-action="Index">
                                <div class = "back-image header__icon" style = "background-image: url(../../media/home.png);"></div>
                                <span>Main</span>
                            </a>
                        </li>
                        <li>
                            <a class = "header__menu-element pointer" asp-area="" asp-controller="Assignment" asp-action="Index">
                                <div class = "back-image header__icon" style = "background-image: url(../../media/task.png);"></div>
                                <span>Tasks</span>
                            </a>
                        </li>
                        <li>
                            <a class = "header__menu-element pointer" asp-area="" asp-controller="Materials" asp-action="Index">
                                <div class = "back-image header__icon" style = "background-image: url(../../media/book-of-black-cover-closed.png);"></div>
                                <span>Materials</span>
                            </a>
                        </li>
                        <li>
                            <a class = "header__menu-element pointer" asp-area="" asp-controller="Roles" asp-action="Index">
                                <div class = "back-image header__icon" style = "background-image: url(../../media/information-button.png);"></div>
                                <span>Roles</span>
                            </a>
                        </li>
                        <li>
                            <a class="header__menu-element pointer" asp-area="" asp-controller="Mark" asp-action="Index" asp-route-sortby="">
                                <div class = "back-image header__icon" style = "background-image: url(../../media/a-plus-test-result-of-school.png);"></div>
                                <span>My marks</span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="header__account set-center">
                    <div class = "header__menu-element">
                        <div class = "back-image account-icon pointer" style = "background-image: url(../../media/ukraine.png);"></div>
                        <div class = "header__switcher-theme pointer" onclick="change_theme()" style = "background-image: url(../../media/dark-mode.png);"></div>
                    </div>
                    <div class="header__account-user">
                        <div class = "header__account-image">
                            <img src="../../media/user.png" alt="Avatar">
                        </div>
                        <div class = "header__account-row">
                            <partial name="_LoginPartial.cshtml" />
                            @*<div class="header__account-row" align = "right">Владислав Л.В</div>
                            <div class="header__account-row" align = "right"> <span class = "pointer logout-link">Logout</span> </div>*@
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="container">
            <main role="main">
                @RenderBody()
            </main>
        </div>

        <footer class="footer__row">
            <div class="container">
                &copy; 2022 - KNUStudySystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/js/scripts.js"></script>
        @RenderSection("Scripts", required: false)
    </body>
</html>